name: Translate specification

on: 
  pull_request:
    paths:
      - 'product_specification/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check for [skip translate] commit message
        id: check_skip_translate
        run: |
          if git log -1 --pretty=%B | grep -q '\[skip translate\]'; then
            echo "::set-output name=skip_translate::true"
          else
            echo "::set-output name=skip_translate::false"
          fi

      - name: Run AI Translate
        if: steps.check_skip_translate.outputs.skip_translate == 'false'
        run: deno task ai_translate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
          REPO: ${{ github.event.pull_request.base.repo.name }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}

      - name: Commit and push changes
        if: steps.check_skip_translate.outputs.skip_translate == 'false'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Add translated files"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
