name: Translate specification

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run AI Translate
        run: deno task ai_translate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
