name: textlint
on: 
  pull_request:
    paths:
      - '**/*.md'

jobs:
  textlint_review:
    name: textlint_review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Run textlint
        run: |
          git diff origin/${{ github.event.pull_request.base.ref }} HEAD --diff-filter=AM --name-only | grep \.md$ > changed_files.txt
          cat changed_files.txt | xargs deno run --allow-env --allow-read --allow-write --allow-sys .github/scripts/textlint.ts

      - name: Run reviewdog
        if: ${{ failure() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat textlint.log \
          | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review
